checklist/urls.py
from django.urls import path
from checklist.views import register_checklist,home_dashboard, auth_checklist

from documents.views import logs
from frontend.views import home


urlpatterns = [
    # URL para tela de dashboard
    path('', home, name='home'),

    # URL para autenticar o registro de checklist
    path('auth/checklist/', auth_checklist, name='auth_checklist'),

    # URL para tela de dashboard
    path('home/dashboard/', home_dashboard, name='home_dashboard'),

    # URL para tela de registro de checklist
    path('register/checklist/', register_checklist, name='register_checklist'),

    # URL para autenticar o registro de checklist
    path('auth/update/checklist/', auth_checklist, name='auth_checklist'),


]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf.urls.static import static
from django.conf import settings    

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('', include('accounts.urls')),
    path('', include('sindico_app.urls')),
    path('', include('checklist.urls')),
    path('', include('maintenance.urls')),
    path('', include('documents.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checklist/models.py
from django.db import models
from django.utils import timezone


class Imagem(models.Model):
    upload = models.ImageField(upload_to='uploads/')

class Checklist(models.Model):
    CONDOMINIOS_CHOICES = [
        ('CondomínioA', 'Condomínio A'),
        ('CondomínioB', 'Condomínio B'),
        ('CondomínioC', 'Condomínio C'),
        # Adicione mais opções conforme necessário
    ]

    PRIORIDADE_CHOICES = [
        ('baixa', 'Baixa'),
        ('média', 'Média'),
        ('alta', 'Alta'),
        ('urgente', 'Urgente'),
    ]

    CATEGORIA_CHOICES = [
        ('estrutural', 'Estrutural'),
        ('administrativo', 'Administrativo'),
        ('seguranca', 'Segurança'),
        ('emergencia', 'Emergência'),
        ('sinistro', 'Sinistro'),
        ('recursosHumanos', 'Recursos Humanos'),
        ('manutencaoRecorrente', 'Manutenção Recorrente'),
        ('limpeza', 'Limpeza'),
        ('jardinagem', 'Jardinagem'),
        ('insetosPragas', 'Insetos/Pragas'),
        ('barulho', 'Barulho'),
        ('vizinhos', 'Relações com Vizinhos'),
        # Adicione mais opções conforme necessário
    ]

    TORRE_CHOICES = [
        ('TorreA', 'Torre A'),
        ('TorreB', 'Torre B'),
        ('TorreC', 'Torre C'),
        # Adicione mais opções conforme necessário
    ]

    ANDAR_CHOICES = [
        ('andar1', 'Andar 1'),
        ('andar2', 'Andar 2'),
        ('andar3', 'Andar 3'),
        # Adicione mais opções conforme necessário
    ]

    APARTAMENTO_CHOICES = [
        ('apartamento1', 'Apartamento n° 1'),
        ('apartamento2', 'Apartamento n° 2'),
        ('apartamento3', 'Apartamento n° 3'),
        # Adicione mais opções conforme necessário
    ]

    AREAS_COMUNS_CHOICES = [
        ('corredorPrincipal', 'Corredor Principal'),
        ('escadas', 'Escadas'),
        ('elevadores', 'Elevadores'),
        ('garagem', 'Garagem'),
        ('salaoFestas', 'Salão de Festas'),
        ('academia', 'Academia'),
        ('piscina', 'Piscina'),
        ('playground', 'Playground'),
        ('quadraEsportiva', 'Quadra Esportiva'),
        ('churrasqueira', 'Churrasqueira'),
        ('salaReunioes', 'Sala de Reuniões'),
        ('salaJogos', 'Sala de Jogos'),
        # Adicione mais opções conforme necessário
    ]

    AREAS_EXTERNAS_CHOICES = [
        ('estacionamento', 'Estacionamento'),
        ('jardim', 'Jardim'),
        ('quadraTennis', 'Quadra de Tênis'),
        ('quadraFutebol', 'Quadra de Futebol'),
        ('patio', 'Pátio'),
        ('ciclovia', 'Ciclovia'),
        # Adicione mais opções conforme necessário
    ]

    STATUS_CHOICES = [
        ('pendente', 'Pendente'),
        ('concluido', 'Concluído'),
        ('em_andamento', 'Em andamento'),
    ]
    
    
    condominio = models.CharField(max_length=100, choices=CONDOMINIOS_CHOICES, null= True, blank= True, default=True)
    torre = models.CharField(max_length=100, choices=TORRE_CHOICES, null= True, blank= True, default=True)
    andar = models.CharField(max_length=100, choices=ANDAR_CHOICES, null= True, blank= True, default=True)
    apartamento = models.CharField(max_length=100, choices=APARTAMENTO_CHOICES,null= True, blank= True, default=True)
    areas_comuns = models.CharField(max_length=100, choices=AREAS_COMUNS_CHOICES, null= True, blank= True, default=True)
    areas_externas = models.CharField(max_length=100, choices=AREAS_EXTERNAS_CHOICES, null= True, blank= True, default=True)
    outros = models.TextField(blank=True)
    prioridade = models.CharField(max_length=100, choices=PRIORIDADE_CHOICES)
    categoria = models.CharField(max_length=100, choices=CATEGORIA_CHOICES, null= True, blank= True, default=True)
    descricao_problema = models.TextField()
    upload = models.ImageField(upload_to='uploads/', blank=True, null=True)
    autor_tipo = models.CharField(max_length=100)
    nome_autor = models.CharField(max_length=100)
    cpf_autor = models.CharField(max_length=14)
    data_upload = models.DateTimeField(default=timezone.now)
    data_checklist = models.DateTimeField(default=timezone.now, blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pendente',blank=True, null=True)
    resolucao_ocorrencia = models.TextField(default="Resolução pendente", blank=True, null=True)
    data_resolucao_ocorrencia = models.DateTimeField(default=timezone.now, blank=True, null=True)


    def __str__(self):
        return f'Checklist #{self.pk} - {self.condominio}'

checklist/forms.py
from django import forms
from .models import Checklist
from django.utils.dateparse import parse_date


class ChecklistForm(forms.ModelForm):
    class Meta:
        model = Checklist
        fields = '__all__'
        widgets = {
            'areas_comuns': forms.Select(choices=Checklist.AREAS_COMUNS_CHOICES),
            'areas_externas': forms.Select(choices=Checklist.AREAS_EXTERNAS_CHOICES),
            'condominio': forms.Select(choices=Checklist.CONDOMINIOS_CHOICES),
            'torre': forms.Select(choices=Checklist.TORRE_CHOICES),
            'andar': forms.Select(choices=Checklist.ANDAR_CHOICES),
            'upload': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            'apartamento': forms.Select(choices=Checklist.APARTAMENTO_CHOICES),
            'outros': forms.TextInput(attrs={'placeholder': 'Especifique o local (ex: Condomínio X, Torre Y, Andar Z, corredor em frente a Área Comum: Academia )'}),
            'prioridade': forms.Select(choices=Checklist.PRIORIDADE_CHOICES),
            'categoria': forms.Select(choices=Checklist.CATEGORIA_CHOICES),
            'descricao_problema': forms.Textarea(attrs={'placeholder': 'Descreva o problema aqui...', 'rows': 4, 'cols': 50}),
            'autor_tipo': forms.Select(choices=[
                ('sindicoAdm', 'Síndico/Administrador'),
                ('morador', 'Morador'),
                ('outros', 'Outros'),
            ]),
        }

    #data do pocorrencia
    def clean_data_criacao_upload(self):
        data_criacao_upload = self.cleaned_data.get('data_criacao_upload')
        if data_criacao_upload:
            try:
                parse_date(data_criacao_upload)
            except ValueError:
                raise forms.ValidationError("Formato de data inválido. Use o formato DD-MM-AAAA.")
        return data_criacao_upload
    
    #data checklist(foto do checklist/ocorrencia)
   # def clean_data_checklist(self):
        data_checklist = self.cleaned_data.get('data_checklist')
        if data_checklist:
            try:
                parse_date(data_checklist)
            except ValueError:
                raise forms.ValidationError("Formato de data inválido. Use o formato DD-MM-AAAA.")
        return data_checklist
         
    def clean_imagem(self):
        upload = self.cleaned_data.get('upload')
        if upload:
            if not upload.name.endswith(('.jpeg', '.png', '.gif')):
                raise forms.ValidationError("Formato de arquivo de imagem inválido. Apenas JPEG, PNG e GIF são suportados.")
        return upload

    def clean_nome_autor(self):
        nome_autor = self.cleaned_data.get('nome_autor')
        if len(nome_autor) < 2:
            raise forms.ValidationError("Por favor, insira um nome válido.")
        if len(nome_autor) > 100:  # Limite máximo de 100 caracteres
            raise forms.ValidationError("O nome não pode ter mais de 100 caracteres.")
        return nome_autor
    
    def clean_descricao_problema(self):
        descricao_problema = self.cleaned_data.get('descricao_problema')
        if len(descricao_problema) > 500:  # Limite máximo de 500 caracteres
            raise forms.ValidationError("A descrição do problema não pode ter mais de 500 caracteres.")
        return descricao_problema

checklist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ChecklistForm
from .models import Checklist
from django.contrib import messages

def auth_checklist(request):
    if request.method == 'POST':
        form = ChecklistForm(request.POST, request.FILES)
        if form.is_valid():
            # Processar os dados do formulário, se necessário
            # Aqui você pode adicionar lógica adicional, como salvar os dados no banco de dados
            form.save()
            # Adiciona uma mensagem de sucesso
            messages.success(request, 'Checklist registrado com sucesso!')
            # Redireciona para a página do dashboard
            return redirect('home_dashboard')
        else:
            # Adiciona uma mensagem de erro caso o formulário não seja válido
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{field}: {error}")
    else:
        form = ChecklistForm()

    return render(request, 'register_checklist.html', {'form': form})

# As funções register_checklist e home_dashboard permanecem iguais
def register_checklist(request):
    form = ChecklistForm()
    return render(request, 'register_checklist.html', {'form': form})

def home_dashboard(request):
    # Contagem de status pendente
    pendente_cont = Checklist.objects.filter(status='pendente').count()

    # Contagem de status concluído
    concluido_cont = Checklist.objects.filter(status='concluido').count()

    contagem_total = Checklist.objects.count()
    return render(request, 'dashboard.html', {
        'pendente': pendente_cont,
        'concluido': concluido_cont,
        'contagem_total':contagem_total
    })


def auth_update_checklist(request, checklist_id):
    checklist = get_object_or_404(Checklist, id=checklist_id)
    
    if request.method == 'POST':
        status = request.POST.get('status')
        resolucao_ocorrencia = request.POST.get('resolucao_ocorrencia')

        if status and resolucao_ocorrencia:
            # Atualiza os campos do checklist
            checklist.status = status
            checklist.resolucao_ocorrencia = resolucao_ocorrencia
            checklist.save()

            messages.success(request, 'Checklist atualizado com sucesso.')
            return redirect('solicitacoes_totais')  # Redireciona para a lista de solicitações totais
        else:
            if not status:
                messages.warning(request, 'É obrigatório mudar o status.')
            if not resolucao_ocorrencia:
                messages.warning(request, 'É obrigatório responder a resolução do problema.')
    else:
        # Caso não seja uma requisição POST, apenas renderiza o template com os dados do checklist
        return render(request, 'manage_solicitacoes.html', {'checklist': checklist})

    # Se houver algum erro de validação ou não for um POST válido, retorna para o template com as mensagens de erro
    return render(request, 'manage_solicitacoes.html', {'checklist': checklist})

checklist/templates/dashboard.html
{% load static%}

<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<!-- Boxicons -->
	<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
	<!-- My CSS -->
	<link rel="stylesheet" href="{% static 'style.css' %}">
	

	<title>IntelliAdmin</title>
	
</head>
<body>


	    <!-- SIDEBAR -->
		<section id="sidebar">
			<a href="{% url 'home' %}" class="brand">
				<i class='bx bxs-check-circle'></i>
				<span class="text">IntelliAdmin</span>
			</a>
			<ul class="side-menu top">
				<li class="active">
					<a href="{% url 'home_dashboard'%}">
						<i class='bx bxs-dashboard'></i>
						<span class="text">Home</span>
					</a>
				</li>
				<li>
					<a href="{% url 'register_checklist' %}">
						<i class='bx bx-check'></i>
						<span class="text">CheckList</span>
					</a>
				</li>
				<li>
					<a href="{% url 'logs' %}">
						<i class='bx bxs-group'></i>
						<span class="text">Logs</span>
					</a>
				</li>
			</ul>
			<ul class="side-menu">
				<li>
					<a href="{% url 'home'%}" class="logout">
						<i class='bx bxs-log-out-circle'></i>
						<span class="text">Logout</span>
					</a>
				</li>
			</ul>
		</section>
		<!-- SIDEBAR -->


	<!-- CONTENT -->
	<section id="content">
		<!-- NAVBAR -->
		<nav>
			<i class='bx bx-menu' ></i>
			<a href="#" class="nav-link">Categories</a>
			<form action="#">
				<div class="form-input">
					<input type="search" placeholder="Search...">
					<button type="submit" class="search-btn"><i class='bx bx-search' ></i></button>
				</div>
			</form>
			<input type="checkbox" id="switch-mode" hidden>
			<label for="switch-mode" class="switch-mode"></label>
			<a href="#" class="notification">
				<i class='bx bxs-bell' ></i>
				<span class="num">8</span>
			</a>
			<a href="#" class="profile">
				<box-icon name='user' color='#007bff' ></box-icon>
			</a>
		</nav>
		<!-- NAVBAR -->

		{% if messages %}
			<div class="messages">
    			{% for message in messages %}
    		<div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}" role="alert">
        		{{ message }}
    		</div>
    			{% endfor %}
			</div>
		{% endif %}

		<!-- MAIN -->
		<main>
			
			<div class="head-title">
				<div class="left">
					<h1>Dashboard</h1>
					
				</div>
				<a href="#" class="btn-download">
					<i class='bx bxs-cloud-download' ></i>
					<span class="text">Download PDF</span>
				</a>
			</div>

				<ul class="box-info">
					<li id="itens">
						<i class='bx bxs-calendar-check'></i>
						<span class="text">
								<h3>{{ concluido }}</h3>
								<p>Solicitações Concluídas</p>
						</span>
					</li>
					<li id="itens">
						<i class='bx bxs-group'></i>
						<span class="text">
							<a href="{% url 'solicitacoes_totais' %}" class="button">
								<h3>{{ contagem_total }}</h3>
								<p>Solicitações Totais</p>
							</a>
						</span>
					</li>
					<li id="itens">
						<i class='bx bxs-dollar-circle'></i>
						<span class="text">
								<h3>{{ pendente }}</h3>
								<p>Solicitações Pendentes</p>
						</span>
					</li>
				</ul>
		</main>
		<!-- MAIN -->
	</section>
	<!-- CONTENT -->
	

	<script src="{% static 'script.js' %}"></script>
</body>
</html>

checklist/templates/register_checklist.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Boxicons -->
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&family=Roboto:wght@400;500&display=swap" rel="stylesheet">

    <!--BOOTSTRAP-->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">


    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'custom.css' %}">

    <title>IntelliAdmin</title>
</head>
<body>

        <!-- SIDEBAR -->
        <section id="sidebar">
            <a href="{% url 'home' %}" class="brand">
                <i class='bx bxs-check-circle'></i>
                <span class="text">IntelliAdmin</span>
            </a>
            <ul class="side-menu top">
                <li class="active">
                    <a href="{% url 'home_dashboard'%}">
                        <i class='bx bxs-dashboard'></i>
                        <span class="text">Home</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'register_checklist' %}">
                        <i class='bx bx-check'></i>
                        <span class="text">CheckList</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'logs'%}">
                        <i class='bx bxs-group'></i>
                        <span class="text">Logs</span>
                    </a>
                </li>
            </ul>
            <ul class="side-menu">
                <li>
                    <a href="{% url 'home'%}" class="logout">
                        <i class='bx bxs-log-out-circle'></i>
                        <span class="text">Logout</span>
                    </a>
                </li>
            </ul>
        </section>
        <!-- SIDEBAR -->

    <!-- CONTENT -->
    <section id="content">
        <!-- NAVBAR -->
        <nav>
            <i class='bx bx-menu' ></i>
            <a href="#" class="nav-link">Categories</a>
            <form action="#">
                <div class="form-input">
                    <input type="search" placeholder="Search...">
                    <button type="submit" class="search-btn"><i class='bx bx-search' ></i></button>
                </div>
            </form>
            <input type="checkbox" id="switch-mode" hidden>
            <label for="switch-mode" class="switch-mode"></label>
            <a href="#" class="notification">
                <i class='bx bxs-bell' ></i>
                <span class="num">8</span>
            </a>
            <a href="#" class="profile">
                <box-icon name='user' color='#007bff' ></box-icon>
            </a>
        </nav>
        
<!-- Exibição de mensagens de erro ou sucesso -->
        {% if messages %}
            {% for message in messages %}
             <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}" role="alert">
                {{ message }}
             </div>
            {% endfor %}
        {% endif %}
        
        <!-- NAVBAR -->
        <!-- FORMULÁRIO -->
    <form method="POST" enctype="multipart/form-data" id="checklist-form" enctype="multipart/form-data" action="{% url 'auth_checklist' %}">
    {% csrf_token %}


    
    <h1>Checklist <i class='bx bx-check-circle' ></i></h1>
    <hr class="section-divider">

    <div class="form-group">
        <label for="id_condominio"> <h3>Informações do Condomínio <i class='bx bx-building-house'></i></h3></label>
        <select name="condominio" id="id_condominio">
            <option value="" >Escolha o Condomínio</option>
            <option value="CondomínioA">Condomínio A</option>
            <option value="CondomínioB">Condomínio B</option>
            <option value="CondomínioC">Condomínio C</option>
        </select>
    </div>

    <div class="form-group">
        <label for="id_torre">Torre </label>
        <select name="torre" id="id_condominio">
            <option value="">Escolha a Torre </option>
            <option value="TorreA">Torre A</option>
            <option value="TorreB">Torre B</option>
            <option value="TorreC">Torre C</option>
            <!--adicionar opção outros, que seja possível ter uma options "outros" que tenha um input com o name e id dessa option-->
        </select>
    </div>
    
    <div class="form-group">
        <label for="id_andar">Andar:</label>
        <select name="andar" id="id_andar">
            <option value="">Escolha o Andar</option>
            <option value="andar1">Andar 1</option>
            <option value="andar2">Andar 2</option>
            <option value="andar3">Andar 3</option>
           <!--adicionar opção outros, que seja possível ter uma options "outros" que tenha um input com o name e id dessa option-->
        </select>
    </div>
    <div class="form-group">
        <label for="id_apartamento">Apartamento:</label>
        <select name="apartamento" id="id_apartamento">
            <option value="">Escolha o Apartamento</option>
            <option value="apartamento1">Apartamento n° 1</option>
            <option value="apartamento2">Apartamento n° 2</option>
            <option value="apartamento3">Apartamento n° 3</option>
             <!--adicionar opção outros, que seja possível ter uma options "outros" que tenha um input com o name e id dessa option-->
        </select>
    </div>
    <div class="form-group">
        <label for="areas_comuns">Áreas Comuns:</label>
        <select id="areas_comuns" name="areas_comuns">
            <option value="">Escolha a Área Comum</option>
            <option value="corredorPrincipal">Corredor Principal</option>
            <option value="escadas">Escadas</option>
            <option value="elevadores">Elevadores</option>
            <option value="garagem">Garagem</option>
            <option value="salaoFestas">Salão de Festas</option>
            <option value="academia">Academia</option>
            <option value="piscina">Piscina</option>
            <option value="playground">Playground</option>
            <option value="quadraEsportiva">Quadra Esportiva</option>
            <option value="churrasqueira">Churrasqueira</option>
            <option value="salaReunioes">Sala de Reuniões</option>
            <option value="salaJogos">Sala de Jogos</option>
        </select>
    </div>
    
    <div class="form-group">
        <label for="areas_externas">Áreas Externas:</label>
        <select id="areas_externas" name="areas_externas">
            <option value="">Escolha a Área Externa</option>
            <option value="estacionamento">Estacionamento</option>
            <option value="jardim">Jardim</option>
            <option value="quadraTennis">Quadra de Tênis</option>
            <option value="quadraFutebol">Quadra de Futebol</option>
            <option value="patio">Pátio</option>
            <option value="ciclovia">Ciclovia</option>
        </select>
    </div>
    
    <div class="form-group">
        <label for="outros">Outros:</label>
        <input type="text" name="outros" id="id_outros" placeholder="Especifique o local (ex: Condomínio X, Torre Y, Andar Z, corredor em frente a Área Comum: Academia )" >
        </div>
    </div>
    
    <h3>Detalhes da Ocorrência <i class='bx bx-error-circle'></i></h3>
    <hr class="section-divider">
    <div class="form-group">
        <label for="id_apartamento">Prioridade:</label>
        <select name="prioridade" id="id_apartamento">
            <option value="" disabled>Escolha a Prioridade</option>
            <option value="baixa">Baixa</option>
            <option value="média">Média</option>
            <option value="alta">Alta</option>
            <option value="urgente">Urgente</option>
        </select>
    </div>
    
    <div class="form-group">
        <label for="id_categoria">Categoria do Problema:</label>
        <select name="categoria" id="id_categoria">
            <option value="" disabled>Escolha a Categoria</option>
            <option value="estrutural">Estrutural</option>
            <option value="administrativo" >Administrativo</option>
            <option value="seguranca">Segurança</option>
            <option value="emergencia">Emergência</option>
            <option value="sinistro">Sinistro</option>
            <option value="recursosHumanos">Recursos Humanos</option>
            <option value="manutencaoRecorrente">Manutenção Recorrente</option>
            <option value="limpeza">Limpeza</option>
            <option value="jardinagem">Jardinagem</option>
            <option value="insetosPragas">Insetos/Pragas</option>
            <option value="barulho">Barulho</option>
            <option value="vizinhos">Relações com Vizinhos</option>
            <!-- Adicione outras opções conforme necessário -->
        </select>
    </div>
    
    
    <div class="form-group">
        <label for="id_descricao">Descrição do Problema:
        </label>
            <div class="custom-textarea"></div>
                <textarea id="id_descricao" name="descricao_problema" placeholder="Descreva o problema aqui..." rows="4" cols="50" required></textarea>
            </div>    
    </div>
    
    <div class="form-group">
        <label for="upload">Adicionar upload:</label>
        <input type="file" name="upload" id="upload" required>
    </div>

    <div class="form-group">
        <label for="id_data_criacao">Data do Upload</label>
        <input type="date" name="data_upload" id="id_data_upload" class="form-control" required>
    </div>
    

    <h3>Autor da Ocorrência  <i class='bx bx-user'></i></h3>
    <hr class="section-divider">
    <div class="form-group">
        <label for="id_autor_tipo">Tipo de Autor </label>
        <select name="autor_tipo" id="id_autor_tipo">
            <option value="sindicoAdm">Síndico/Administrador</option>
            <option value="morador">Morador</option>
            <option value="outros">Outros</option>
        </select>
    </div>
    
    <div class="form-group">
        <label for="id_nome_autor">Nome:</label>
        <input type="text" name="nome_autor" id="id_nome_autor" required>
    </div>
    
    <div class="form-group">
        <label for="id_cpf_autor">CPF:</label>
        <input type="text" name="cpf_autor" id="id_cpf_autor" required>
    </div>

    
    
    <div class="form-group">
        <input type="submit" value="Enviar">
    </div>
</form>

 
    </section>
    <!-- CONTENT -->

    <script src="{% static 'script.js' %}"></script>
</body>
</html>