maintenance/urls.py
from django.urls import path
from maintenance.views import request_totais, manage_solicit
from checklist.views import register_checklist, auth_update_checklist
from frontend.views import home


urlpatterns = [
    # URL para tela de dashboard
    path('', home, name= 'home'),

    # URL para tela de solicitações totais
    path('solicitacoes/totais/', request_totais, name='solicitacoes_totais'),

    # URL para tela de registro de checklist
    path('register/checklist/', register_checklist, name='register_checklist'),

    # URL para tela edição com as informações do checklist
    path('manage/solicit/<int:checklist_id>', manage_solicit, name='manage_solicit'),

    # URL para autenticação update de checklist
    path('auth/update/checklist/<int:checklist_id>/', auth_update_checklist, name='auth_update_checklist')

]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf.urls.static import static
from django.conf import settings    

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('', include('accounts.urls')),
    path('', include('sindico_app.urls')),
    path('', include('checklist.urls')),
    path('', include('maintenance.urls')),
    path('', include('documents.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checklist/models.py
from django.db import models
from django.utils import timezone


class Imagem(models.Model):
    upload = models.ImageField(upload_to='uploads/')

class Checklist(models.Model):
    CONDOMINIOS_CHOICES = [
        ('CondomínioA', 'Condomínio A'),
        ('CondomínioB', 'Condomínio B'),
        ('CondomínioC', 'Condomínio C'),
        # Adicione mais opções conforme necessário
    ]

    PRIORIDADE_CHOICES = [
        ('baixa', 'Baixa'),
        ('média', 'Média'),
        ('alta', 'Alta'),
        ('urgente', 'Urgente'),
    ]

    CATEGORIA_CHOICES = [
        ('estrutural', 'Estrutural'),
        ('administrativo', 'Administrativo'),
        ('seguranca', 'Segurança'),
        ('emergencia', 'Emergência'),
        ('sinistro', 'Sinistro'),
        ('recursosHumanos', 'Recursos Humanos'),
        ('manutencaoRecorrente', 'Manutenção Recorrente'),
        ('limpeza', 'Limpeza'),
        ('jardinagem', 'Jardinagem'),
        ('insetosPragas', 'Insetos/Pragas'),
        ('barulho', 'Barulho'),
        ('vizinhos', 'Relações com Vizinhos'),
        # Adicione mais opções conforme necessário
    ]

    TORRE_CHOICES = [
        ('TorreA', 'Torre A'),
        ('TorreB', 'Torre B'),
        ('TorreC', 'Torre C'),
        # Adicione mais opções conforme necessário
    ]

    ANDAR_CHOICES = [
        ('andar1', 'Andar 1'),
        ('andar2', 'Andar 2'),
        ('andar3', 'Andar 3'),
        # Adicione mais opções conforme necessário
    ]

    APARTAMENTO_CHOICES = [
        ('apartamento1', 'Apartamento n° 1'),
        ('apartamento2', 'Apartamento n° 2'),
        ('apartamento3', 'Apartamento n° 3'),
        # Adicione mais opções conforme necessário
    ]

    AREAS_COMUNS_CHOICES = [
        ('corredorPrincipal', 'Corredor Principal'),
        ('escadas', 'Escadas'),
        ('elevadores', 'Elevadores'),
        ('garagem', 'Garagem'),
        ('salaoFestas', 'Salão de Festas'),
        ('academia', 'Academia'),
        ('piscina', 'Piscina'),
        ('playground', 'Playground'),
        ('quadraEsportiva', 'Quadra Esportiva'),
        ('churrasqueira', 'Churrasqueira'),
        ('salaReunioes', 'Sala de Reuniões'),
        ('salaJogos', 'Sala de Jogos'),
        # Adicione mais opções conforme necessário
    ]

    AREAS_EXTERNAS_CHOICES = [
        ('estacionamento', 'Estacionamento'),
        ('jardim', 'Jardim'),
        ('quadraTennis', 'Quadra de Tênis'),
        ('quadraFutebol', 'Quadra de Futebol'),
        ('patio', 'Pátio'),
        ('ciclovia', 'Ciclovia'),
        # Adicione mais opções conforme necessário
    ]

    STATUS_CHOICES = [
        ('pendente', 'Pendente'),
        ('concluido', 'Concluído'),
        ('em_andamento', 'Em andamento'),
    ]
    
    
    condominio = models.CharField(max_length=100, choices=CONDOMINIOS_CHOICES, null= True, blank= True, default=True)
    torre = models.CharField(max_length=100, choices=TORRE_CHOICES, null= True, blank= True, default=True)
    andar = models.CharField(max_length=100, choices=ANDAR_CHOICES, null= True, blank= True, default=True)
    apartamento = models.CharField(max_length=100, choices=APARTAMENTO_CHOICES,null= True, blank= True, default=True)
    areas_comuns = models.CharField(max_length=100, choices=AREAS_COMUNS_CHOICES, null= True, blank= True, default=True)
    areas_externas = models.CharField(max_length=100, choices=AREAS_EXTERNAS_CHOICES, null= True, blank= True, default=True)
    outros = models.TextField(blank=True)
    prioridade = models.CharField(max_length=100, choices=PRIORIDADE_CHOICES)
    categoria = models.CharField(max_length=100, choices=CATEGORIA_CHOICES, null= True, blank= True, default=True)
    descricao_problema = models.TextField()
    upload = models.ImageField(upload_to='uploads/', blank=True, null=True)
    autor_tipo = models.CharField(max_length=100)
    nome_autor = models.CharField(max_length=100)
    cpf_autor = models.CharField(max_length=14)
    data_upload = models.DateTimeField(default=timezone.now)
    data_checklist = models.DateTimeField(default=timezone.now, blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pendente',blank=True, null=True)
    resolucao_ocorrencia = models.TextField(default="Resolução pendente", blank=True, null=True)
    data_resolucao_ocorrencia = models.DateTimeField(default=timezone.now, blank=True, null=True)


    def __str__(self):
        return f'Checklist #{self.pk} - {self.condominio}'

maintenance/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
#from django.http import JsonResponse
from django.views.decorators.http import require_POST
from checklist.models import Checklist

def request_totais(request):
    # Renderiza a página de solicitacoes totais
    status = request.GET.get('status')
    # Obter todos os checklists ordenados pela data
    checklist = Checklist.objects.all().order_by('-data_checklist')

    # Filtrar checklists pelo status, se fornecido
    if status and status != 'todos':
         checklist = checklist.filter(status=status)

    # Paginação dos checklists
    paginator = Paginator(checklist, 9)  # 9 checklists por página
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
    }

    return render(request, 'solicitacoes_totais.html', context)

def manage_solicit(request, checklist_id):
    # Buscar o checklist pelo ID
    checklist = get_object_or_404(Checklist, id=checklist_id)

    # Renderizar a página de edição com as informações do checklist
    return render(request, 'manage_solicitacoes.html', {'checklist': checklist})

maintenance/templates/manage_solicitacoes.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'custom.css' %}">
    <title>IntelliAdmin</title>
</head>

<body>
    <!-- SIDEBAR -->
    <section id="sidebar">
        <a href="{% url 'home' %}" class="brand">
            <i class='bx bxs-check-circle'></i>
            <span class="text">IntelliAdmin</span>
        </a>
        <ul class="side-menu top">
            <li class="active">
                <a href="{% url 'home_dashboard'%}">
                    <i class='bx bxs-dashboard'></i>
                    <span class="text">Home</span>
                </a>
            </li>
            <li>
                <a href="{% url 'register_checklist' %}">
                    <i class='bx bx-check'></i>
                    <span class="text">CheckList</span>
                </a>
            </li>
            <li>
                <a href="{% url 'logs'%}">
                    <i class='bx bxs-group'></i>
                    <span class="text">Logs</span>
                </a>
            </li>
        </ul>
        <ul class="side-menu">
            <li>
                <a href="{% url 'home'%}" class="logout">
                    <i class='bx bxs-log-out-circle'></i>
                    <span class="text">Logout</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- SIDEBAR -->

    <!-- CONTENT -->
    <section id="content">
        <!-- NAVBAR -->
        <nav>
            <a href="#" class="nav-link">Categories</a>
            <form action="#">
                <div class="form-input">
                    <input type="search" placeholder="Search...">
                    <button type="submit" class="search-btn"><i class='bx bx-search'></i></button>
                </div>
            </form>
            <input type="checkbox" id="switch-mode" hidden>
            <label for="switch-mode" class="switch-mode"></label>
            <i class='bx bx-menu bx-menu-open'></i>
            <a href="#" class="notification">
                <i class='bx bxs-bell'></i>
                <span class="num">8</span>
            </a>
            <a href="#" class="profile">
                <box-icon name='user' color='#007bff'></box-icon>
            </a>
        </nav>
        <!-- NAVBAR -->

        <!-- INFORMAÇÕES REGISTRADAS -->
        <div class="container mt-4">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <h2>Informações Registradas<box-icon name='file' type='solid' height="40px"></box-icon></h2>
                    <br>

                    <!-- Informações do Local -->
                    <section>
                        <h3>Local da Ocorrência</h3>
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <th>Condomínio</th>
                                    <td>{{ checklist.condominio }}</td>
                                </tr>
                                <tr>
                                    <th>Torre</th>
                                    <td>{{ checklist.torre }}</td>
                                </tr>
                                <tr>
                                    <th>Andar</th>
                                    <td>{{ checklist.andar }}</td>
                                </tr>
                                <tr>
                                    <th>Apartamento</th>
                                    <td>{{ checklist.apartamento }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </section>

                    <!-- Informações da Área -->
                    <section>
                        <h3>Área da Ocorrência</h3>
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <th>Áreas Comuns</th>
                                    <td>{{ checklist.areas_comuns }}</td>
                                </tr>
                                <tr>
                                    <th>Áreas Externas</th>
                                    <td>{{ checklist.areas_externas }}</td>
                                </tr>
                                <tr>
                                    <th>Outros</th>
                                    <td>{{ checklist.outros }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </section>

                    <!-- Detalhes da Ocorrência -->
                    <section>
                        <h3>Detalhes da Ocorrência</h3>
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <th>Prioridade</th>
                                    <td>{{ checklist.prioridade }}</td>
                                </tr>
                                <tr>
                                    <th>Categoria</th>
                                    <td>{{ checklist.categoria }}</td>
                                </tr>
                                <tr>
                                    <th>Descrição do Problema</th>
                                    <td>{{ checklist.descricao_problema }}</td>
                                </tr>
                                {% if checklist.upload %}
                                <tr>
                                    <th>Imagem registrada:</th>
                                    
                                    <td><img src="{{ checklist.upload.url }}" alt="Imagem da Ocorrência" height="200">
                                    </td>
                                </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </section>

                    <!-- Informações do Autor -->
                    <section>
                        <h3>Autor da Ocorrência</h3>
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <th>Autor Tipo</th>
                                    <td>{{ checklist.autor_tipo }}</td>
                                </tr>
                                <tr>
                                    <th>Nome do Autor</th>
                                    <td>{{ checklist.nome_autor }}</td>
                                </tr>
                                <tr>
                                    <th>CPF do Autor</th>
                                    <td>{{ checklist.cpf_autor }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </section>

                    <!-- Outras Informações -->
                    <section>
                        <h3>Resolução da Ocorrência</h3>
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <th>Data do Checklist</th>
                                    <td>{{ checklist.data_checklist }}</td>
                                </tr>
                                <tr>
                                    <th>Data da Resolução da Ocorrência</th>
                                    <td>{{ checklist.data_resolucao_ocorrencia }}</td>
                                </tr>
                                <tr>
                                    <th>Como foi resolvida a ocorrência</th>
                                    <td>{{ checklist.resolucao_ocorrencia }}</td>
                                </tr>
                                <tr>
                                    <th>Status</th>
                                    <td>{{ checklist.status }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
        </div>
        <!-- INFORMAÇÕES REGISTRADAS -->

        <!-- Feedbacks de erro ou sucesso! -->
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}"
                role="alert">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <!-- RESOLUÇÃO DA OCORRÊNCIA -->
        <div class="container mt-4">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <h2>Resolução da Ocorrência</h2>
                    <form action="{% url 'auth_update_checklist' checklist_id=checklist.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="resolucao_ocorrencia">Como foi resolvido:</label>
                            <textarea class="form-control" id="resolucao_ocorrencia"
                                name="resolucao_ocorrencia"></textarea>
                        </div>

                        <!-- Campo oculto para o ID do checklist -->
                        <input type="hidden" id="checklistId" name="checklistId" value="{{ checklist.id }}">
                        <!-- Campo oculto para o ID do usuário logado -->
                        <input type="hidden" id="userId" name="userId" value="{{ request.user.id }}">

                        <label for="status">Status:</label>
                        <select class="form-control" id="status" name="status">
                            <option value="">Selecione</option>
                            <option value="concluido">Concluído</option>
                            <option value="andamento">Em Andamento</option>
                            <option value="pendente">Pendente</option>
                        </select>
                        <br>
                        <button type="submit" class="btn btn-success">Salvar</button>
                        <a href="{% url 'solicitacoes_totais' %}">
                            <button type="button" class="btn btn-danger">Cancelar</button>
                        </a>
                    </form>
                </div>
            </div>
        </div>
        <!-- RESOLUÇÃO DA OCORRÊNCIA -->

    </section>
    <!-- CONTENT -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'script.js' %}"></script>
    <script src="{% static 'modal.js' %}"></script>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script src="{% static 'app.js' %}"></script>
</body>

</html>

maintenance/templates/solicitacoes_totais.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">



    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <title>IntelliAdmin</title>
</head>

<body>
    <!-- SIDEBAR -->
    <section id="sidebar">
        <a href="{% url 'home' %}" class="brand">
            <i class='bx bxs-check-circle'></i>
            <span class="text">IntelliAdmin</span>
        </a>
        <ul class="side-menu top">
            <li class="active">
                <a href="{% url 'home_dashboard'%}">
                    <i class='bx bxs-dashboard'></i>
                    <span class="text">Home</span>
                </a>
            </li>
            <li>
                <a href="{% url 'register_checklist' %}">
                    <i class='bx bx-check'></i>
                    <span class="text">CheckList</span>
                </a>
            </li>
            <li>
				<a href="{% url 'logs'%}">
					<i class='bx bxs-group'></i>
					<span class="text">Logs</span>
				</a>
			</li>
        </ul>
        <ul class="side-menu">
            <li>
                <a href="{% url 'home'%}" class="logout">
                    <i class='bx bxs-log-out-circle'></i>
                    <span class="text">Logout</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- SIDEBAR -->

    <!-- CONTENT -->
    <section id="content">
        <!-- NAVBAR -->
        <nav>
            <i class='bx bx-menu'></i>
            <a href="#" class="nav-link">Categories</a>
            <form action="#">
                <div class="form-input">
                    <input type="search" placeholder="Search...">
                    <button type="submit" class="search-btn"><i class='bx bx-search'></i></button>
                </div>
            </form>
            <input type="checkbox" id="switch-mode" hidden>
            <label for="switch-mode" class="switch-mode"></label>
            <a href="#" class="notification">
                <i class='bx bxs-bell'></i>
                <span class="num">8</span>
            </a>
            <a href="#" class="profile">
                <box-icon name='user' color='#007bff'></box-icon>
            </a>
        </nav>
        <!-- NAVBAR -->

        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}"
                role="alert">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <!-- MAIN CONTENT -->
        <main class="container mt-4">
            <div class="row">
                <div class="col-12">
                    <h2>Registro de Solicitações</h2>
                    <br>
                    <div class="row">
                        {% for checklist in page_obj %}
                        <div class="col-md-4 mb-3">
                            <div class="card" data-status="{{ checklist.status }}">
                                <div class="card-header d-flex justify-content-between align-items-center {% if checklist.status == 'concluido' %}bg-success
                              {% elif checklist.status == 'pendente' %}bg-danger
                              {% elif checklist.status == 'andamento' %}bg-warning
                              {% endif %}">
                                    <span class="text-white">
                                        <b> Status: {{ checklist.get_status_display }}</b>
                                    </span>
                                    <a href="{% url 'manage_solicit' checklist.id %}">
                                        <button class="edit-btn" data-id="{{ checklist.id }}"
                                            style="background: none; border: none; cursor: pointer;">
                                            <box-icon name='edit' color="#ffffff"></box-icon>
                                        </button>
                                    </a>

                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">{{ checklist.get_condominio_display }}</h5>
                                    <p class="card-text">Autor: {{ checklist.nome_autor }}</p>
                                    <p class="card-text">Data: {{ checklist.data_checklist }}</p>
                                    <p class="card-text">Prioridade: {{ checklist.get_prioridade_display }}</p>
                                    <p class="card-text">Categoria: {{ checklist.get_categoria_display }}</p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                    <!-- MAIN CONTENT -->

                    <!-- NAVEGAÇÃO DA PÁGINA -->
                    <nav aria-label="Navegação de página exemplo">
                        <ul class="pagination">

                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1" aria-label="Primeira">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Primeira</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                    aria-label="Anterior">
                                    <span aria-hidden="true">&lsaquo;</span>
                                    <span class="sr-only">Anterior</span>
                                </a>
                            </li>
                            {% endif %}

                            {% for num in page_obj.paginator.page_range %}
                            <li class="page-item {% if num == page_obj.number %}active{% endif %}">
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                            {% endfor %}

                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Próximo">
                                    <span aria-hidden="true">&rsaquo;</span>
                                    <span class="sr-only">Próximo</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"
                                    aria-label="Última">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Última</span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                    <!--END NAVEGAÇÃO DA PÁGINA -->
                </div>
            </div>
        </main>
        <!-- END MAIN CONTENT -->

    </section>
    <!-- CONTENT -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>   
    <script src="{% static 'script.js' %}"></script>
</body>

</html>